const initialLayout = {
  A1: { color: "w", piece: "rook" },
  A2: { color: "w", piece: "pawn" },
  A7: { color: "b", piece: "pawn" },
  A8: { color: "b", piece: "rook" },
  B1: { color: "w", piece: "knight" },
  B2: { color: "w", piece: "pawn" },
  B7: { color: "b", piece: "pawn" },
  B8: { color: "b", piece: "knight" },
  C1: { color: "w", piece: "bishop" },
  C2: { color: "w", piece: "pawn" },
  C7: { color: "b", piece: "pawn" },
  C8: { color: "b", piece: "bishop" },
  D1: { color: "w", piece: "queen" },
  D2: { color: "w", piece: "pawn" },
  D7: { color: "b", piece: "pawn" },
  D8: { color: "b", piece: "queen" },
  E1: { color: "w", piece: "king" },
  E2: { color: "w", piece: "pawn" },
  E7: { color: "b", piece: "pawn" },
  E8: { color: "b", piece: "king" },
  F1: { color: "w", piece: "bishop" },
  F2: { color: "w", piece: "pawn" },
  F7: { color: "b", piece: "pawn" },
  F8: { color: "b", piece: "bishop" },
  G1: { color: "w", piece: "knight" },
  G2: { color: "w", piece: "pawn" },
  G7: { color: "b", piece: "pawn" },
  G8: { color: "b", piece: "knight" },
  H1: { color: "w", piece: "rook" },
  H2: { color: "w", piece: "pawn" },
  H7: { color: "b", piece: "pawn" },
  H8: { color: "b", piece: "rook" },
};
export default initialLayout;
